Build toolbar and headline sections
ebidien/portfolio-mobile-first pull request #1
Opened 2022-12-07 02:01 UTC by ebidien

## Build toolbar and headline sections
The following changes were made to this feature branch:
- The repository was set up with the Microverse **README.md** template and **HTML&CSS linter** configuration, and the required media were downloaded from **Template 1** of the 5 Microverse Figma Portfolio templates provided as samples
- The **toolbar** section was built with a logo and menu icon styled with **CSS Flexbox**.
- The **headline** section was built and styled with **CSS Flexbox**.
- **Social media icons** were added below the headline introductory text.
- **Button interactions** were implemented - changing the mouse pointer, the menu's background color, and social media icons on **mouse hover**.

2022-12-07 15:27 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @ebidien, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 15:27 UTC, anagudelogu commented on index.html
> +        </nav>
You did a great job working on this section! 🚀 However, there's still room to improve:

- [ ] Please consider wrapping this section in a `<header>` tag, this will provide a better semantic value to browsers and assistive technologies such as screen readers about the content of this section! 🤓 

- [ ] By convention, the "Logo" of the page links to the home page. Following this convention is important to provide a great user experience! Please consider changing the `<div>` element to an `<a>` one to achieve this functionality! 🤓 

- [ ] Please consider working a little more on the styling of this header 🎨. At the moment, you could add some horizontal padding to match the spacing given in the template! Having a good UI design will potentially increase the attention of future recruiters! 🤓 

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/206214941-3b796e0c-78db-41f0-b956-ba8ffbb3f621.png) | ![image](https://user-images.githubusercontent.com/77069011/206214773-14664abb-301c-42fb-aeb6-7f05025bc42e.png) |
 

Please consider applying those changes! 🛠️

2022-12-07 15:27 UTC, anagudelogu commented on index.html
> +        </section>
You did a great job working on the headline section! 💯 Here are possible improvements:

- [ ] Instead of using a `<p>` tag to wrap your title, you could use an `<hx>` tag. In this case, as this is the main title, consider using an `<h1>`. This will provide better semantic value, as it is not representing a paragraph but a title. 🤓 

- [ ] Same for the "Let's Connect" subtitle. As it represents the "title" for social media icons, I think it would be better to wrap it inside an `<h2>` tag instead of a `<p>`. 🤓 

- [ ] For the social media icons, as it is representing a list of icons, I suggest you use the HTML tag to represent just that, the `<ul>` instead of a generic `<div>`. Also, there's a special tag for list items, the `<li>`. The purpose of this social media list is that users who view your profile have an easy way of connecting with you, so please consider adding `<a>` tags to link to your social media profiles! 🤓 

e.g.:
```HTML
<ul>
  <li><a href="Your_Twitter_Profile_Link"><img src="twitter.png" alt="twitter" /></a></li>
  <li><a href="Your_LinkedIn_Profile_Link"><img src="linkedin.png" alt="linkedin" /></a></li>
  ... 
</ul>
```

- [ ] I would also suggest you add some horizontal padding to this section (especially on the left) to avoid content from being that close to the edges and match the given Figma design 🎨:

|Template|Your design|
|---|---|
| ![image](https://user-images.githubusercontent.com/77069011/206219928-b6fb5557-dd08-475e-8dfd-05c15455bb19.png) | ![image](https://user-images.githubusercontent.com/77069011/206219654-c37051e3-7184-4c83-b4c2-8b8f5a0c68d9.png) |


Please apply these changes! 🤓 🛠️

2022-12-08 16:59 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @ebidien, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 16:59 UTC, anagudelogu commented on index.html
> +        </header>
- [ ] **[OPTIONAL]:** Great job implementing the changes requested! 🚀 You removed the `<nav>` tag wrapping your logo and the hamburger button. Please keep it so you can provide information about the navigational content! I strongly suggest you implement this. 🤓 🛠️ 

```suggestion
        <header class="toolbar">
            <nav>
                <a class="logo" href="index.html">ebidien</a>
                <div class="main-menu">
                    <img src="menu-button.svg" alt="Main Menu">
                </div>
            </nav>
        </header>

```

2022-12-08 17:18 UTC, ebidien commented on index.html
> +        </header>
Thanks for the review @anagudelogu, your review was quite helpful. Keep up the good work in being an excellent communicator!

2022-12-08 17:19 UTC, merged